# Generated by Django 5.0.6 on 2024-06-07 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Platform', models.CharField(max_length=50)),
                ('About_Platform', models.CharField(max_length=50)),
                ('Website_Platform', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Review_Text', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movies_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Movie_Rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('Movie_ReleaseYear', models.DateField()),
                ('Movie_Language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], max_length=7)),
                ('Movie_Subtitle', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=7)),
                ('Movie_Size', models.PositiveIntegerField()),
                ('Movie_Quality', models.CharField(choices=[('480P', '480P'), ('720P', '720P'), ('1080p', '1080p')], max_length=5)),
                ('Movie_Format', models.CharField(choices=[('MKV', 'MKV')], max_length=3)),
                ('Movie_Story', models.CharField(max_length=1000)),
                ('is_Movie_Webseries', models.BooleanField(default=False)),
                ('is_Movie_DualAudio', models.BooleanField(default=False)),
                ('Movie_Created', models.DateTimeField(auto_now_add=True)),
                ('Movie_Upload', models.FileField(upload_to='Movies/')),
                ('Movies_ScreenShots', models.ImageField(upload_to='Movie_ScreenShot/')),
                ('Movie_Platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to='Movie_App.platforms_model')),
                ('Movies_Review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies_Review', to='Movie_App.review_model')),
            ],
        ),
    ]
