# Generated by Django 5.0.6 on 2024-06-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_model',
            name='Movies_Review',
        ),
        migrations.AddField(
            model_name='review_model',
            name='Review_Movie_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='Movie_App.movies_model'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review_model',
            unique_together={('Review_Movie_name', 'user')},
        ),
    ]
