# Generated by Django 5.0.6 on 2024-06-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0003_alter_review_model_review_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_model',
            name='Review_Movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie_name', to='Movie_App.movies_model'),
        ),
    ]
