# Generated by Django 5.0.6 on 2024-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0005_alter_review_model_review_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_model',
            name='Movie_Platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='Movie_App.platforms_model'),
        ),
    ]
