# Generated by Django 5.0.6 on 2024-06-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0006_alter_movies_model_movie_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_model',
            name='Movie_Platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to='Movie_App.platforms_model'),
        ),
        migrations.AlterField(
            model_name='review_model',
            name='Review_Movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='Movie_App.movies_model'),
        ),
    ]
